# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Akshit Arora
email: akshit.arora@colorado.edu
description: Thoughts
baseurl: "/Gravity/" # the subpath of your site, e.g. /blog
url: "https://aroraakshit.github.io" # the base hostname & protocol for your site
twitter_username: AkshitArora1995
github_username:  aroraakshit

# Build settings
markdown: kramdown
